# Glitch-Community CircleCI Config
#
# Note: Version 2.1 is required in order to use orbs.

version: 2.1
# the Glitch project sets up an orb for communicating with Slack here. Might be useful.
# orbs:
#   slack: circleci/slack@3.3.0
jobs:
  lint_and_build:
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      BUILD_TYPE: static
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: 
          name: prep-for-artifacts
          command: mkdir -p $CIRCLE_ARTIFACTS
      - run:
          name: setup-ssh
          command: cp ./ci/ssh.config ~/.ssh/config
      - run:
          name: update-pnpm
          command: "sudo npm install -g pnpm@3.x"
      - restore_cache:
          keys:
            # in Glitch we key on .Branch, but this is probably just as good
            # diff branches will probably have different checksums
            - deps-{{ checksum "shrinkwrap.yaml" }}
      - run:
          name: pnpm-install
          command: pnpm install
      - save_cache:
          # Glitch save a bunch of other stuff here, but I don't think we need it
          paths:
            - node_modules
          key: deps-{{ checksum "shrinkwrap.yaml" }}
      - run:
          # note to self - i wonder why this is right here? It's _after_ the cache save both here and in Glitch - 
          # are we linting stuff that gets stored in / restored from the cache? should we lint _before_ we save the cache then?
          name: eslint
          command: pnpm run lint
      # do we care about the artifacts?
      - run:
          name: build
          command: pnpm run build
# in retrospect I _think_ we're storing this here so that we can rely on the build's outputs in the tests without having to rebuild
      - save_cache:
          paths:
            - build
          key: build-{{ .Revision }}
      - run:
          name: compress-artifacts
          command: cd /home/circleci/project && tar --exclude=./.git --exclude=./node_modules -czf /home/circleci/build.tar.gz .
# this should make the compresed build available for the deploy
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - build.tar.gz
# we may not need this at all in fact
      - store_artifacts:
          path: /home/circleci/build.tar.gz # can't use env vars in store_artifacts per https://discuss.circleci.com/t/can-i-use-environment-variables-in-store-artifacts/11226
  # not being run as of 2019-11-19
  integration_tests:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "shrinkwrap.yaml" }}
      - restore_cache:
          keys:
            - build-{{ .Revision }}
      - run:
          name: update-pnpm
          command: "sudo npm install -g pnpm@3.x"
      - run:
          name: pnpm-install
          command: pnpm install
      - run:
          name: cypress
          command: pnpm run cy:ci
  # should we be storing these reports anywhere? Maybe mocha generates its own?
  unit_tests:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "shrinkwrap.yaml" }}
      - restore_cache:
          keys:
            - build-{{ .Revision }}
      - run:
          name: update-pnpm
          command: "sudo npm install -g pnpm@3.x"
      - run:
          name: pnpm-install
          command: pnpm install
      - run:
          name: mocha
          command: pnpm run test

  ###########################
  # new for comunity infra  #
  ###########################
  deploy:
    working_directory: /home/circleci/project
    shell: /bin/bash --login

    environment:
      # empty set
    
    docker:
      - image: circleci/node:10-browsers  # same as the other community jobs

    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      # - run:
      #     name: where-am-i
      #     command: pwd && ls -la
      - run: cp ./ci/ssh.config ~/.ssh/config
      - run:
          name: deploy-to-hosts
          command:  ./ci/deploy.sh

workflows:
  version: 2.1
  regular-workflow:
    jobs:
      - lint_and_build
      - unit_tests:
          requires:
            - lint_and_build
      - deploy:
          requires:
            - unit_tests
          filters:
            branches:
              only:
                staging
